#include <asm/cacheflush.h>
#include <linux/uaccess.h>
#include <linux/kernel.h>
#include <linux/vmalloc.h>
#include <asm/pgtable.h>
#include <asm/cacheflush.h>
#include <asm/page.h>
#include <linux/mm.h>
#include <asm/insn.h>
#include "include/common_data.h"

int (*insn_decode_ptr)(struct insn *, const void *, int, enum insn_mode) = NULL;

extern int (*core_kernel_text_ptr)(unsigned long);
extern bool (*is_module_text_address_ptr)(unsigned long);

static int disass_target(void *target)
{
	struct insn insn;
	int off = 0, ret;

	while (off < LONG_JMP_CODE_LEN) {
		ret = insn_decode_ptr(&insn, target + off, MAX_INSN_SIZE, INSN_MODE_KERN);
		if (ret)
			return ret;
		off += insn.length;
	}
	return off;
}

/* \x90: nop */
int fill_nop_for_target(void *fill_dest, void *target);
int fill_nop_for_target(void *fill_dest, void *target)
{
	int actual_len = disass_target(target);
	if (actual_len < 0)
		return actual_len;
	if (actual_len > HIJACK_SIZE) {
		printk(KERN_ALERT"Maybe long(>=%d) instructions encountered before %llx\n",
			HIJACK_SIZE - LONG_JMP_CODE_LEN, (u64)(target + actual_len));
		return -1;
	}
	memset(fill_dest + LONG_JMP_CODE_LEN, '\x90', actual_len - LONG_JMP_CODE_LEN);
	return 0;
}

int fill_nop_for_code_space(void *fill_dest, void *target);
int fill_nop_for_code_space(void *fill_dest, void *target)
{
	int actual_len = disass_target(target);
	if (actual_len < 0)
		return actual_len;
	if (actual_len > HIJACK_SIZE) {
		printk(KERN_ALERT"Maybe long(>=%d) instructions encountered before %llx\n",
			HIJACK_SIZE - LONG_JMP_CODE_LEN, (u64)(target + actual_len));
		return -1;
	}
	memset(fill_dest + actual_len, '\x90', HIJACK_SIZE - actual_len);
	return 0;
}

/* skip the check */
bool check_target_can_hijack(void *target);
bool check_target_can_hijack(void *target)
{
	return true;
}

/*
* Since we are inserting jump instrcutions, if we insert in kernel area(to jump out of kernel),
* we should use phys_to_page(__pa(target)), if we insert in kernel_module(to jump back to kernel), 
* we should use vmalloc_to_page(target) instead
*/
static int remap_write_range(void *target, void *source, int size)
{
	struct page *page = NULL;
	void *new_target = NULL;

	if ((((unsigned long)target + size) ^ (unsigned long)target) & PAGE_MASK) {
		printk(KERN_ALERT"Try to write word across page boundary %lx\n",
			(unsigned long)target);
		return -EFAULT;
	}

	if (core_kernel_text_ptr && is_module_text_address_ptr) {
		if (core_kernel_text_ptr((unsigned long)target)) {
			page = virt_to_page(target);
		} else if (is_module_text_address_ptr((unsigned long)target)) {
			page = vmalloc_to_page(target);
		} else {
			printk(KERN_ALERT"Try to write to non kernel text address %lx\n",
				(unsigned long)target);
			return -EFAULT;
		}
	} else {
		page = virt_to_page(target);
	}

	if (!page) {
		printk(KERN_ALERT"Cannot get page of address %lx\n",
			(unsigned long)target);
		return -EFAULT;
	}

	new_target = vm_map_ram(&page, 1, -1);
	if (!new_target) {
		printk(KERN_ALERT"Remap address %lx failed\n",
			(unsigned long)target);
		return -EFAULT;
	} else {
		memcpy(new_target + ((unsigned long)target & (~ PAGE_MASK)), source, size);
		vm_unmap_ram(new_target, 1);
		flush_icache_range((unsigned long)target, (unsigned long)target + size);
		return 0;
	}
}

int hook_write_range(void *target, void *source, int size);
int hook_write_range(void *target, void *source, int size)
{
	long ret = remap_write_range(target, source, size);
	return (int)ret;
}

const uint8_t endbr64[] = {0xf3, 0x0f, 0x1e, 0xfa, 0x90};

void *find_sym(const char *);
static bool intel_ibt_enabled(void)
{
	return memcmp(find_sym, endbr64, 4) ? false : true;
}

#define MAX_INSN_LEN 15

/*
 * Generated by AI, to identify nop inst and length
 * return:
 *   >0 : nop instruction length
 *    0 : not nop
 */
int x86_get_nop_length(const uint8_t *code)
{
    const uint8_t *p = code;

    /* -------- prefix parse -------- */

    while (1) {

        switch (*p) {

        case 0x66:  /* operand size */
        case 0x67:  /* address size */

        case 0xF2:
        case 0xF3:  /* rep */

        case 0x2E:
        case 0x36:
        case 0x3E:
        case 0x26:
        case 0x64:
        case 0x65:  /* segment */

            p++;

            if (p - code >= MAX_INSN_LEN)
                return 0;

            continue;

        default:
            break;
        }

        break;
    }

    /* -------- single byte nop -------- */

    if (*p == 0x90)
        return (p - code) + 1;

    /* -------- multi-byte nop -------- */

    if (p[0] == 0x0F && p[1] == 0x1F) {

        const uint8_t *q = p + 2;

        uint8_t modrm = *q++;

        uint8_t mod = modrm >> 6;
        uint8_t reg = (modrm >> 3) & 7;
        uint8_t rm  = modrm & 7;

        /* must be /0 */
        if (reg != 0)
            return 0;

        int len = (q - code);

        /* -------- SIB -------- */

        if (mod != 3 && rm == 4) {

            uint8_t sib = *q++;
            uint8_t base = sib & 7;

            len++;

            if (mod == 0 && base == 5) {
                q += 4;
                len += 4;
            }
        }

        /* -------- displacement -------- */

        if (mod == 1) {

            q += 1;
            len += 1;

        } else if (mod == 2) {

            q += 4;
            len += 4;

        } else if (mod == 0 && rm == 5) {

            q += 4;
            len += 4;
        }

        return len;
    }

    return 0;
}


int hack_func_ibt(void *func, int *offset);
int hack_func_ibt(void *func, int *offset)
{
	int ret = -EFAULT;
	int i;

	if (!intel_ibt_enabled()) {
		*offset = 0;
		return 0;
	}

	for (i = 0; i < 8; i = i + 4) { 
		if (!memcmp(func - i, endbr64, 4)) {
			*offset = -i;
			return 0;
		}

		switch (x86_get_nop_length(func - i)) {
		case 5:
			ret = hook_write_range(func - i, endbr64, 5);
			*offset = -i;
			return 0;
		case 4:
			ret = hook_write_range(func - i, endbr64, 4);
			*offset = -i;
			return 0;
		}
	}

	return ret;
}

int init_arch(void);
int init_arch(void)
{
	insn_decode_ptr = (void *)prep_callfunc("insn_decode");
	return !insn_decode_ptr;
}
